### ISSUE TITLE
ERROR: Response of login call to /login_sid.lua in initSID was not xml-formatted.

### ISSUE THREAD

**Issue by tonybluem** [carlos22/carddav2fb#13]
Hello,

now I get another Error-Message:

root@meinrechner:/var/www/carddav2fb# php carddav2fb.php
carddav2fb.php 1.11 (2016-05-12) - CardDAV to FRITZ!Box phonebook conversion tool
Copyright (c) 2012-2016 Karl Glatz, Martin Rost, Jens Maus, Johannes Freiburger

```
Retrieving VCards from all CardDAV server(s):
 [0]: http://gustav.duck/owncloud/remote.php/dav/addressbooks/users/tony/kontakte/ .................................................................... 68 VCards retrieved.
  WARNING: No fullname, lastname, orgname or formatted name found!
  WARNING: No fullname, lastname, orgname or formatted name found!
Done.
Converting VCards to FritzBox XML format:
 ...
 VCard: 'AAAA Testkontakt'
  Added phone: +4989666666 (home)
Done.
Upload data to FRITZ!Box @ fritz.duck
PHP Warning:  ftp_mkdir(): /FRITZ/fonpix: File exists. in /var/www/carddav2fb/carddav2fb.php on line 721
 Uploading Phonebook XML to fritz.duck
  ERROR: Response of login call to /login_sid.lua in initSID was not xml-formatted.
```

How can I solve this?

Thank you!

Tony

**Comment by tonybluem** [comment]
Hallo,

ich habe heute fast den ganzen schönen Sonntag damit verbracht carddav2fb zum Laufen zu bringen. Leider bisher ohne Erfolg. Nach einigen überwundenen Hürden scheitere ich nun an dieser Fehlermeldung:

root@meinrechner:/var/www/carddav2fb# php carddav2fb.php
carddav2fb.php 1.11 (2016-05-12) - CardDAV to FRITZ!Box phonebook conversion tool
Copyright (c) 2012-2016 Karl Glatz, Martin Rost, Jens Maus, Johannes Freiburger

Retrieving VCards from all CardDAV server(s):
[0]: http://gustav.duck/owncloud/remote.php/dav/addressbooks/users/tony/kontakte/ .................................................................... 68 VCards retrieved.
WARNING: No fullname, lastname, orgname or formatted name found!
WARNING: No fullname, lastname, orgname or formatted name found!
Done.
Converting VCards to FritzBox XML format:
...
VCard: 'AAAA Testkontakt'
Added phone: +4989666666 (home)
Done.
Upload data to FRITZ!Box @ fritz.duck
PHP Warning: ftp_mkdir(): /FRITZ/fonpix: File exists. in /var/www/carddav2fb/carddav2fb.php on line 721
Uploading Phonebook XML to fritz.duck
ERROR: Response of login call to /login_sid.lua in initSID was not xml-formatted.

Ich habe die aktuellste Version von hier 

https://github.com/carlos22/carddav2fb

installiert. 

FritzBox 7390 mit FRITZ!OS:06.51

Vielen Dank!


Tony

**Comment by carlos22** [comment]
Hast du die Benutzerverwaltung in der Fritzbox aktiviert? Siehe: https://service.avm.de/help/de/FRITZ-Box-Fon-WLAN-7390/011/hilfe_system_user

Ohne diese funktioniert der login nicht. Was wurde in der config als Benutzer angegeben?

**Comment by tonybluem** [comment]
Vielen Dank für die schnelle Antwort.

Ich vermute mit aktivierter Benutzerverwaltung meinst Du: 

System - Fritz!Box-Benutzer - Anmeldung im Heimnetz - 

hier:  Anmeldung mit FRITZ!Box-Benutzernamen und Kennwort aktiviert

Weiterhin habe ich unter 

System - Fritz!Box-Benutzer - Benutzer 

einen Benutzer "carddav2fb" angelegt, der die Rechte

FRITZ!Box Einstellungen 
Sprachnachrichten, Faxnachrichten, FRITZ!App Fon und Anrufliste 
Zugang zu NAS-Inhalten 
Smart Home 

hat.

In der config.php habe ich 

.
$config['fritzbox_ip'] = 'fritz.box';
$config['fritzbox_ip_ftp'] = 'fritz.box';
// user name/password to access Fritz!Box
$config['fritzbox_user'] = 'carddav2fb';
$config['fritzbox_pw'] = 'carddav2fb';
//$config['fritzbox_force_local_login'] = true;

// number of the internal phone book and its name
// 0    - main phone book
// 1..n - additional phone books
$config['phonebook_number'] = '2';
$config['phonebook_name'] = 'phonebookpriv';

Das müsste doch stimmen. Doch woran könnte es liegen?

VG

Tonx

**Comment by carlos22** [comment]
Gute Frage. Also bei mir funktioniert das mit einer Ähnlichen Konfiguration ganz gut. Ich nutze alleridngs Telefonbuch 0 - sollte aber damit nicht wirklich was zu tun haben...

**Comment by tonybluem** [comment]
Hallo Carlos22,

ich habe gerade nochmals auf Telefonbuch 0 umgestellt. Leider kommt die gleiche Fehlermeldung.

Verwendest Du auch FRITZ!OS:06.51?

Vielen Dank!

Tony

**Comment by carlos22** [comment]
Nein aktuell Fritz!OS 06.50.

**Comment by jupiter4fun** [comment]
Is there any progress or work-around ? I encountered the same issue with OS 06.63.
Thanks, Dirk

**Comment by carlos22** [comment]
I don't have the problem with 06.51.

**Comment by jupiter4fun** [comment]
Danke, leider kann ich am OS nichts machen. Habe übrigens eine 6490 (Kabel), aber nicht gebrandet.

**Comment by cploeger** [comment]
Hallo,

auch wenn dieses Issue bereits etwas älter ist, möchte ich euch nicht vorenthalten, wie ich das Problem lösen konnte.

Ich musste lediglich die folgende Zeile auskommentieren:
//$config['fritzbox_force_local_login'] = true;

Damit klappt der Sync jetzt auf meiner 7390 mit FRITZ!OS 6.51

**Comment by JPustkuchen** [comment]
Interessanterweise war bei mir gerade auf einer Fritz!Box 7590 mit FritzOS 07.01 die Lösung diese Zeile wieder einzukommentieren... ;)

**Comment by derkostka** [comment]
Bei mir ebenfalls, danke für die Hinweise
