### ISSUE TITLE
alternative php packages in debian 8

### ISSUE THREAD

**Issue by happyreacer** [carlos22/carddav2fb#20]
i'd like to use the carddav2fb in a debian 8 system, but i dont have the following php-moduls fond:
PHP-ftp
PHP-mbstring

Can i use in debian other php-modules for bring it to work?

Greatings

**Comment by carlos22** [comment]
The names of the packages are different in each distribution and/or version. Sometimes the modules are compiled into php or packaged in different packages.

List of packages in debian stable:
https://packages.debian.org/search?keywords=php5&searchon=names&suite=stable&section=all

The ftp module is either not availabe as package or part of the php5 package itself and only needs to be enabled in php.ini (caution: debian uses some magic here with php5enmod).

**Comment by happyreacer** [comment]
Okay, thanks ist works with Debian 8
