### ISSUE TITLE
Error parsing phone numbers created by nextcloud 15.0.5

### ISSUE THREAD

**Issue by wrohdewald** [carlos22/carddav2fb#33]
I really do not want to delve into PHP, hope you can fix this. It seems carddav2fb cannot parse

`TEL;TYPE=&quot;WORK,VOICE&quot;:+49 1111111&#13;
`

carddav2fb fails, finds no phone number:

 VCard: 'Eyes and more'
  WARNING: no phone entry found. VCard will be ignored.
  Added email:  (home)

Looking into the nextcloud 15.0.5 mysql tables, I find lots of different variants. The one not working in this issue has been created today with nextcloud 15.0.5. Other variants found are:

DAVDROID1.TEL;TYPE=x-mobil:
davdroid1.TEL;TYPE=x-other:
TEL;TYPE=cell:
TEL;TYPE=CELL:
TEL;TYPE=cell;PREF=1:
TEL;TYPE=fax:
TEL;TYPE=FAX:
TEL;TYPE=home:
TEL;TYPE=HOME:
TEL;TYPE=home,PREF:
TEL;TYPE=home;PREF=1:
TEL;TYPE=HOME,VOICE:
TEL;TYPE="HOME,VOICE";VALUE=URI:
TEL;TYPE=OTHER:
TEL;TYPE=PREF,CELL:
TEL;TYPE=PREF\\,CELL:
TEL;TYPE=PREF,HOME:
TEL;TYPE="PREF,WORK":
TEL;TYPE=PREF,WORK:
TEL;TYPE=voice:
TEL;TYPE=work:
TEL;TYPE=WORK:
TEL;TYPE="WORK,VOICE":
TEL;TYPE=WORK,VOICE:
TEL;TYPE=WORK\\,VOICE:

The full unparseable entry from nextcloud 15.0.5:

<vcard>BEGIN:VCARD&#13;
VERSION:3.0&#13;
PRODID:-//Sabre//Sabre VObject 4.1.6//EN&#13;
UID:a049d91d-e283-4878-a863-867094027bfc&#13;
FN:Eyes and more&#13;
ADR;TYPE=HOME:;;;Harburg;;;&#13;
EMAIL;TYPE=HOME:&#13;
TEL;TYPE=&quot;WORK,VOICE&quot;:+49 1111111&#13;
ORG:&#13;
CATEGORIES:PG&#13;
END:VCARD&#13;
</vcard>

carddav2fb works with this one, it finds a phone number:

<vcard>BEGIN:VCARD&#13;
VERSION:3.0&#13;
VERSION:3.0&#13;
VERSION:3.0&#13;
VERSION:3.0&#13;
VERSION:3.0&#13;
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN&#13;
PRODID:-//Sabre//Sabre VObject 3.4.7//EN&#13;
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN&#13;
N:;Postbank;;;;;;;&#13;
UID:5926bec7-b405-4efd-b395-181702c982fa&#13;
REV:2016-01-13T13:02:18+00:00&#13;
FN:Postbank&#13;
CATEGORIES:PG&#13;
TEL;TYPE=WORK:+49 1111111111&#13;
END:VCARD&#13;
</vcard>

**Comment by NorbertRonecker** [comment]
#31 solves the Issue for me.

**Comment by wrohdewald** [comment]
For me too, thank you! I only looked at open issues and ignored the pull requests
